//! Bulk operations for Call entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCallDto;
use crate::application::service::CallService;
use crate::domain::entity::Call;

/// Bulk operation handler for Call entities.
///
/// Wraps `CallService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CallBulkService = GenericBulkService<Call, CreateCallDto, CallService>;

// <<< CUSTOM
// END CUSTOM
