//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod call_bulk;

pub use call_bulk::CallBulkService;

// <<< CUSTOM
// END CUSTOM
