//! Domain layer
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.

pub mod entity;
pub mod event;
pub mod repositories;
pub mod services;
pub mod specifications;

// Re-export commonly used types
pub use entity::*;
pub use repositories::*;
pub use services::*;
pub use specifications::*;

// <<< CUSTOM
// END CUSTOM
