//! Skeleton Module Routes
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Composes all entity routes into a single Axum router.

use axum::Router;

use crate::presentation::http::create_example_routes;
use crate::Module;

/// Create stateless routes for the skeleton module.
pub fn create_stateless_routes(module: &Module) -> Router<()> {
    Router::new()
        .merge(create_example_routes(module.example_service.clone()))
}

/// Get all routes for the module, mounted under `/api/v1`.
pub fn get_routes(module: &Module) -> Router<()> {
    Router::new().nest("/api/v1", create_stateless_routes(module))
}
