//! Event Store Infrastructure
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Provides event sourcing infrastructure.

mod event_envelope;
mod event_store;
mod snapshot_store;

// Re-exports
pub use event_envelope::{EventEnvelope, EventMetadata, StoredEvent};
pub use event_store::{EventStore, PostgresEventStore};
pub use snapshot_store::{Snapshot, SnapshotStore, PostgresSnapshotStore, SnapshotStrategy};
