//! Call DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Call;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::CallDirection;
use crate::domain::entity::CallStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Call
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCallDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    pub direction: CallDirection,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "from_number")]
    pub from_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "to_number")]
    pub to_number: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "agent_id")]
    pub agent_id: Option<Uuid>,
    pub status: CallStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "external_id")]
    pub external_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_type")]
    pub subject_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "started_at")]
    pub started_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answered_at")]
    pub answered_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "ended_at")]
    pub ended_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "duration_seconds")]
    pub duration_seconds: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "recording_url")]
    pub recording_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Call
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCallDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    pub direction: CallDirection,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "from_number")]
    pub from_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "to_number")]
    pub to_number: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "agent_id")]
    pub agent_id: Option<Uuid>,
    pub status: CallStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "external_id")]
    pub external_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_type")]
    pub subject_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "started_at")]
    pub started_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answered_at")]
    pub answered_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "ended_at")]
    pub ended_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "duration_seconds")]
    pub duration_seconds: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "recording_url")]
    pub recording_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Call
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCallDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub direction: Option<CallDirection>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "from_number")]
    pub from_number: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "to_number")]
    pub to_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "agent_id")]
    pub agent_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<CallStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "external_id")]
    pub external_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "subject_type")]
    pub subject_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "started_at")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "answered_at")]
    pub answered_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "ended_at")]
    pub ended_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "duration_seconds")]
    pub duration_seconds: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "recording_url")]
    pub recording_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl PatchCallDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.direction.is_some() || self.from_number.is_some() || self.to_number.is_some() || self.party_id.is_some() || self.agent_id.is_some() || self.status.is_some() || self.external_id.is_some() || self.subject_type.is_some() || self.subject_id.is_some() || self.started_at.is_some() || self.answered_at.is_some() || self.ended_at.is_some() || self.duration_seconds.is_some() || self.recording_url.is_some() || self.notes.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Call entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CallResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub direction: CallDirection,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub from_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub to_number: String,
    pub party_id: Option<Uuid>,
    pub agent_id: Option<Uuid>,
    pub status: CallStatus,
    pub external_id: Option<String>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub started_at: DateTime<Utc>,
    pub answered_at: Option<DateTime<Utc>>,
    pub ended_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub duration_seconds: i32,
    pub recording_url: Option<String>,
    pub notes: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Call entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CallListResponseDto {
    /// List of items
    pub items: Vec<CallResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CallListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CallResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CallSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub direction: CallDirection,
    pub from_number: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Call> for CallResponseDto {
    fn from(entity: Call) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            direction: entity.direction,
            from_number: entity.from_number,
            to_number: entity.to_number,
            party_id: entity.party_id,
            agent_id: entity.agent_id,
            status: entity.status,
            external_id: entity.external_id,
            subject_type: entity.subject_type,
            subject_id: entity.subject_id,
            started_at: entity.started_at,
            answered_at: entity.answered_at,
            ended_at: entity.ended_at,
            duration_seconds: entity.duration_seconds,
            recording_url: entity.recording_url,
            notes: entity.notes,
            metadata: entity.metadata,
        }
    }
}

impl From<Call> for CallSummaryDto {
    fn from(entity: Call) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            direction: entity.direction,
            from_number: entity.from_number,
            created_at,
        }
    }
}

impl From<CreateCallDto> for Call {
    fn from(dto: CreateCallDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            direction: dto.direction,
            from_number: dto.from_number,
            to_number: dto.to_number,
            party_id: dto.party_id,
            agent_id: dto.agent_id,
            status: dto.status,
            external_id: dto.external_id,
            subject_type: dto.subject_type,
            subject_id: dto.subject_id,
            started_at: dto.started_at,
            answered_at: dto.answered_at,
            ended_at: dto.ended_at,
            duration_seconds: dto.duration_seconds,
            recording_url: dto.recording_url,
            notes: dto.notes,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Call> for CallResponseDto {
    fn from(entity: &Call) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            direction: entity.direction.clone(),
            from_number: entity.from_number.clone(),
            to_number: entity.to_number.clone(),
            party_id: entity.party_id.clone(),
            agent_id: entity.agent_id.clone(),
            status: entity.status.clone(),
            external_id: entity.external_id.clone(),
            subject_type: entity.subject_type.clone(),
            subject_id: entity.subject_id.clone(),
            started_at: entity.started_at.clone(),
            answered_at: entity.answered_at.clone(),
            ended_at: entity.ended_at.clone(),
            duration_seconds: entity.duration_seconds.clone(),
            recording_url: entity.recording_url.clone(),
            notes: entity.notes.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCallDto> for Call {
    fn from_create_dto(dto: CreateCallDto) -> backbone_core::ServiceResult<Self> {
        Ok(Call::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCallDto> for Call {
    fn apply_update(mut self, dto: UpdateCallDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.direction = dto.direction;
        self.from_number = dto.from_number;
        self.to_number = dto.to_number;
        self.party_id = dto.party_id;
        self.agent_id = dto.agent_id;
        self.status = dto.status;
        self.external_id = dto.external_id;
        self.subject_type = dto.subject_type;
        self.subject_id = dto.subject_id;
        self.started_at = dto.started_at;
        self.answered_at = dto.answered_at;
        self.ended_at = dto.ended_at;
        self.duration_seconds = dto.duration_seconds;
        self.recording_url = dto.recording_url;
        self.notes = dto.notes;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Call here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
