//! Application service for Call entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `call_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCallDto, UpdateCallDto};
use crate::domain::entity::Call;
use crate::infrastructure::persistence::CallRepository;

/// Application service for Call entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `call_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CallServiceCustom {
///     inner: Arc<CallService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CallService = GenericCrudService<
    Call,
    CreateCallDto,
    UpdateCallDto,
    CallRepository,
>;

// <<< CUSTOM
// END CUSTOM
