//! Application service for Example entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `example_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::application::dto::{CreateExampleDto, UpdateExampleDto};
use crate::domain::entity::Example;
use crate::infrastructure::persistence::ExampleRepository;

/// Application service for Example entities.
///
/// All standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `example_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ExampleServiceCustom {
///     inner: Arc<ExampleService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ExampleService = GenericCrudService<
    Example,
    CreateExampleDto,
    UpdateExampleDto,
    ExampleRepository,
>;

// <<< CUSTOM
// END CUSTOM
