//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod call_service;

// <<< CUSTOM
pub mod telephony_events;
pub mod telephony_write_service;
// END CUSTOM

pub use call_service::CallService;
// <<< CUSTOM
pub use telephony_events::{
    CallLogged, LoggingSink, MissedCall, TelephonyEvent, TelephonyEventSink,
};
pub use telephony_write_service::{CallOutcome, InboundCdr, TelephonyError, TelephonyWriteService};
// END CUSTOM