-- Call Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the telephony.calls table.
-- Customize this file to add your initial data.

-- INSERT INTO telephony.calls (
--     id,
--     company_id,
--     direction,
--     from_number,
--     to_number,
--     party_id,
--     agent_id,
--     status,
--     external_id,
--     subject_type,
--     subject_id,
--     started_at,
--     answered_at,
--     ended_at,
--     duration_seconds,
--     recording_url,
--     notes,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO telephony.calls (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

