-- Enum types for the skeleton module
-- Generated by backbone-schema

-- Create example_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'example_status') THEN
        CREATE TYPE example_status AS ENUM ('active', 'inactive');
    END IF;
END
$$;
