-- Migration: Create examples table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS examples (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    status example_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_examples_status ON examples (status);
CREATE INDEX IF NOT EXISTS idx_examples_name ON examples (name);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_examples_metadata_gin ON examples USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_examples_metadata_deleted_at ON examples ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
CREATE OR REPLACE FUNCTION examples_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS examples_audit_timestamp_trigger ON examples;
CREATE TRIGGER examples_audit_timestamp_trigger
    BEFORE INSERT OR UPDATE ON examples
    FOR EACH ROW EXECUTE FUNCTION examples_audit_timestamp();
