-- Company RLS fence for telephony module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for telephony.calls
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE telephony.calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE telephony.calls FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS calls_company_isolation ON telephony.calls;
CREATE POLICY calls_company_isolation ON telephony.calls
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

