-- Migration: Create calls table
-- Generated by metaphor-schema

-- Create call_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'call_direction') THEN
        CREATE TYPE call_direction AS ENUM ('inbound', 'outbound');
    END IF;
END
$$;

-- Create call_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'call_status') THEN
        CREATE TYPE call_status AS ENUM ('ringing', 'answered', 'completed', 'missed', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS telephony;

CREATE TABLE IF NOT EXISTS telephony.calls (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    direction call_direction NOT NULL,
    from_number TEXT NOT NULL,
    to_number TEXT NOT NULL,
    party_id UUID,
    agent_id UUID,
    status call_status NOT NULL DEFAULT 'ringing',
    external_id TEXT,
    subject_type TEXT,
    subject_id UUID,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    answered_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    duration_seconds INTEGER NOT NULL DEFAULT 0,
    recording_url TEXT,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_calls_company_id_external_id ON telephony.calls (company_id, external_id);

CREATE INDEX IF NOT EXISTS idx_calls_company_id_party_id ON telephony.calls (company_id, party_id);

CREATE INDEX IF NOT EXISTS idx_calls_subject_type_subject_id ON telephony.calls (subject_type, subject_id);

CREATE INDEX IF NOT EXISTS idx_calls_status ON telephony.calls (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_calls_metadata_gin ON telephony.calls USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_calls_metadata_deleted_at ON telephony.calls ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_calls_metadata_created_at ON telephony.calls ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_calls_metadata_updated_at ON telephony.calls ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION telephony.calls_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS calls_insert_audit ON telephony.calls;
CREATE TRIGGER calls_insert_audit BEFORE INSERT ON telephony.calls
    FOR EACH ROW EXECUTE FUNCTION telephony.calls_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS calls_update_audit ON telephony.calls;
CREATE TRIGGER calls_update_audit BEFORE UPDATE ON telephony.calls
    FOR EACH ROW EXECUTE FUNCTION telephony.calls_audit_timestamp();
