-- Audit Triggers Migration for telephony module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Call (telephony.calls)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION telephony.calls_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS calls_insert_audit ON telephony.calls;
CREATE TRIGGER calls_insert_audit BEFORE INSERT ON telephony.calls
    FOR EACH ROW EXECUTE FUNCTION telephony.calls_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS calls_update_audit ON telephony.calls;
CREATE TRIGGER calls_update_audit BEFORE UPDATE ON telephony.calls
    FOR EACH ROW EXECUTE FUNCTION telephony.calls_audit_timestamp();

