-- Enum types for telephony module
-- Generated by metaphor-schema

-- Create call_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'call_direction') THEN
        CREATE TYPE call_direction AS ENUM ('inbound', 'outbound');
    END IF;
END
$$;

-- Create call_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'call_status') THEN
        CREATE TYPE call_status AS ENUM ('ringing', 'answered', 'completed', 'missed', 'failed');
    END IF;
END
$$;

