//! Domain events for Call entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Call;

/// Domain events for Call — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Call>)` variant.
pub type CallEvent = CrudEvent<Call>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Call events.
pub type CallEventPublisher = Arc<dyn CrudEventPublisher<Call> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCallEventPublisher = NoOpCrudEventPublisher<Call>;
