//! Event handler trait for Call events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CallEvent;

/// Event handler for Call events.
/// Implement this trait to react to Call lifecycle events.
pub trait CallEventHandler: EventHandler<CallEvent> {}
