//! Event subscriber type aliases for Telephony module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::CallEvent;

/// Subscriber for Call events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type CallEventSubscriber = GenericEventSubscriber<CallEvent>;

// <<< CUSTOM
// END CUSTOM
