//! Repository trait for Call aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Call aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{Call, CallDirection, CallStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CallPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CallPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CallPaginatedResult {
    pub data: Vec<Call>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CallFilter {
    pub direction: Option<CallDirection>,
    pub from_number: Option<String>,
    pub to_number: Option<String>,
    pub party_id: Option<Uuid>,
    pub agent_id: Option<Uuid>,
    pub status: Option<CallStatus>,
    pub external_id: Option<String>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
    pub recording_url: Option<String>,
    pub notes: Option<String>,
}

impl CallFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.direction.is_some()
            || self.from_number.is_some()
            || self.to_number.is_some()
            || self.party_id.is_some()
            || self.agent_id.is_some()
            || self.status.is_some()
            || self.external_id.is_some()
            || self.subject_type.is_some()
            || self.subject_id.is_some()
            || self.recording_url.is_some()
            || self.notes.is_some()
    }
}

/// Repository trait for Call aggregate
///
/// This trait defines the persistence contract for Call entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CallRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new call entity
    async fn save(&self, entity: &Call) -> Result<Call>;

    /// Find call by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Call>>;

    /// Find all call entities
    async fn find_all(&self) -> Result<Vec<Call>>;

    /// Update call by ID
    async fn update(&self, id: &str, entity: &Call) -> Result<Option<Call>>;

    /// Delete call by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List call with pagination
    async fn list(&self, params: CallPaginationParams) -> Result<CallPaginatedResult>;

    /// List call with pagination and filters
    async fn list_with_filters(
        &self,
        params: CallPaginationParams,
        filters: CallFilter,
    ) -> Result<CallPaginatedResult>;

    /// Count all call entities
    async fn count(&self) -> Result<u64>;

    /// Count call entities matching filters
    async fn count_with_filters(&self, filters: CallFilter) -> Result<u64>;

    /// Check if call exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete call by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted call by ID
    async fn restore(&self, id: &str) -> Result<Option<Call>>;

    /// List soft-deleted call entities
    async fn list_deleted(&self, params: CallPaginationParams) -> Result<CallPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save call entities
    async fn bulk_save(&self, entities: &[Call]) -> Result<Vec<Call>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
