//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.

pub mod call_repository;

// Re-exports
pub use call_repository::{CallFilter, CallPaginatedResult, CallPaginationParams, CallRepository};
