//! Repository for Call entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Call, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Call;

/// Table name for Call entities
pub const TABLE_NAME: &str = "telephony.calls";

/// Repository for Call entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CallRepository(
    backbone_orm::GenericCrudRepository<Call, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CallRepository {
    type Target = backbone_orm::GenericCrudRepository<Call, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CallRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CallRepository, Call, soft_delete);
