//! Repository for Call entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below are the home for every hand-written Call SQL statement (4-layer rule: services orchestrate,
//! repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Call, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::{DateTime, Utc};
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Call;

/// Table name for Call entities
pub const TABLE_NAME: &str = "telephony.calls";

/// Repository for Call entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CallRepository(
    backbone_orm::GenericCrudRepository<Call, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CallRepository {
    type Target = backbone_orm::GenericCrudRepository<Call, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CallRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a provider CDR insert writes.
///
/// Mirrors the raw column shape rather than the `Call` entity: `direction`/`status` arrive from a
/// provider webhook as free strings and are cast at the DB (`$3::call_direction`, `$8::call_status`),
/// which is what lets a bad provider value fail as a DB error instead of a deserialize panic.
pub struct NewCallRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub direction: &'a str,
    pub from_number: &'a str,
    pub to_number: &'a str,
    pub party_id: Option<Uuid>,
    pub agent_id: Option<Uuid>,
    pub status: &'a str,
    pub external_id: Option<&'a str>,
    pub subject_type: Option<&'a str>,
    pub subject_id: Option<Uuid>,
    pub started_at: DateTime<Utc>,
    pub answered_at: Option<DateTime<Utc>>,
    pub ended_at: Option<DateTime<Utc>>,
    pub duration_seconds: i32,
    pub recording_url: Option<&'a str>,
    pub notes: Option<&'a str>,
}

/// The dedup probe's projection: the original call's id + its recorded talk-time.
pub struct CallOutcomeRow {
    pub id: Uuid,
    pub duration_seconds: i32,
}

/// Hand-written Call SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl CallRepository {
    /// Probe for an already-recorded provider CDR — the (company, external_id) dedup fast path.
    ///
    /// A read outside any transaction: takes the pool and runs `fetch_optional_row_scoped` so the
    /// RLS fence (ADR-0008) applies. The explicit `company_id = $1` filter stays as defense-in-depth.
    pub async fn find_outcome_by_external_id(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        external_id: &str,
    ) -> Result<Option<CallOutcomeRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                "SELECT id, duration_seconds FROM telephony.calls WHERE company_id=$1 AND external_id=$2")
                .bind(company_id).bind(external_id),
        ).await?;
        Ok(row.map(|r| CallOutcomeRow { id: r.get("id"), duration_seconds: r.get("duration_seconds") }))
    }

    /// Re-read the original after a losing `ON CONFLICT DO NOTHING` race. Same scoping as the probe.
    pub async fn fetch_outcome_by_external_id(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        external_id: &str,
    ) -> Result<CallOutcomeRow, sqlx::Error> {
        let row = company_scope::fetch_one_row_scoped(
            pool,
            sqlx::query(
                "SELECT id, duration_seconds FROM telephony.calls WHERE company_id=$1 AND external_id=$2")
                .bind(company_id).bind(external_id),
        ).await?;
        Ok(CallOutcomeRow { id: row.get("id"), duration_seconds: row.get("duration_seconds") })
    }

    /// Insert a CDR idempotently on (company, external_id). `Ok(None)` = a concurrent writer won the
    /// race and the caller should re-read the original.
    ///
    /// Takes the CALLER'S connection so the insert and the outbox stage commit as one unit. The caller
    /// binds the company on that connection (`bind_company_on`) before calling — don't re-bind here.
    pub async fn insert_cdr(
        &self,
        conn: &mut sqlx::PgConnection,
        c: &NewCallRow<'_>,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        sqlx::query_scalar(
            r#"INSERT INTO telephony.calls
                 (id, company_id, direction, from_number, to_number, party_id, agent_id, status,
                  external_id, subject_type, subject_id, started_at, answered_at, ended_at,
                  duration_seconds, recording_url, notes)
               VALUES ($1,$2,$3::call_direction,$4,$5,$6,$7,$8::call_status,$9,$10,$11,$12,$13,$14,$15,$16,$17)
               ON CONFLICT (company_id, external_id) DO NOTHING
               RETURNING id"#,
        )
        .bind(c.id).bind(c.company_id).bind(c.direction).bind(c.from_number).bind(c.to_number)
        .bind(c.party_id).bind(c.agent_id).bind(c.status).bind(c.external_id)
        .bind(c.subject_type).bind(c.subject_id).bind(c.started_at).bind(c.answered_at).bind(c.ended_at)
        .bind(c.duration_seconds).bind(c.recording_url).bind(c.notes)
        .fetch_optional(conn)
        .await
    }

    /// Attach a live call to what it concerns. Returns rows affected (0 = no such live call in scope).
    ///
    /// ID-only: no company argument. Runs `execute_scoped`, so it rides a connection carrying the
    /// caller's `app.company_id` and another company's call simply is not matched. A non-request
    /// caller (event/job) must wrap this in `with_company_scope(Some(company_id))` or it fails closed.
    pub async fn update_subject(
        &self,
        pool: &PgPool,
        call_id: Uuid,
        subject_type: &str,
        subject_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE telephony.calls SET subject_type=$2, subject_id=$3
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(call_id).bind(subject_type).bind(subject_id),
        ).await?;
        Ok(done.rows_affected())
    }
}

backbone_core::impl_crud_repository!(CallRepository, Call, soft_delete);
