//! Shared validation types — re-exported from backbone-core.
//!
//! Generated by metaphor-schema. Do not edit manually.

pub use backbone_core::{
    EntityValidator, MaxLength, NonNegative, OptionalNotBlank, Regex, RequiredString, RequiredUuid,
    ValidationError, ValidationErrors,
};

/// Convenience result type for validation.
pub type ValidationResult = Result<(), ValidationErrors>;
