//! Example domain entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Reference entity showing the canonical layout of a Backbone aggregate:
//! strongly-typed id, FromRow-friendly struct, builder, patch, audit metadata,
//! and the standard trait impls expected by `backbone-core` and `backbone-orm`.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

use super::AuditMetadata;
use super::ExampleStatus;

/// Strongly-typed ID for Example
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ExampleId(pub Uuid);

impl ExampleId {
    pub fn new(id: Uuid) -> Self { Self(id) }
    pub fn generate() -> Self { Self(Uuid::new_v4()) }
    pub fn into_inner(self) -> Uuid { self.0 }
}

impl std::fmt::Display for ExampleId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::str::FromStr for ExampleId {
    type Err = uuid::Error;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(Self(Uuid::parse_str(s)?))
    }
}

impl From<Uuid> for ExampleId {
    fn from(id: Uuid) -> Self { Self(id) }
}

impl From<ExampleId> for Uuid {
    fn from(id: ExampleId) -> Self { id.0 }
}

impl AsRef<Uuid> for ExampleId {
    fn as_ref(&self) -> &Uuid { &self.0 }
}

impl std::ops::Deref for ExampleId {
    type Target = Uuid;
    fn deref(&self) -> &Self::Target { &self.0 }
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Example {
    pub id: Uuid,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub status: ExampleStatus,
    #[serde(default)]
    #[sqlx(json)]
    pub metadata: AuditMetadata,
}

impl Example {
    /// Create a builder for Example
    pub fn builder() -> ExampleBuilder {
        ExampleBuilder::default()
    }

    /// Create a new Example with required fields
    pub fn new(name: String, status: ExampleStatus) -> Self {
        Self {
            id: Uuid::new_v4(),
            name,
            description: None,
            status,
            metadata: AuditMetadata::default(),
        }
    }

    pub fn id(&self) -> &Uuid { &self.id }

    pub fn typed_id(&self) -> ExampleId { ExampleId(self.id) }

    pub fn created_at(&self) -> Option<&DateTime<Utc>> { self.metadata.created_at.as_ref() }

    pub fn updated_at(&self) -> Option<&DateTime<Utc>> { self.metadata.updated_at.as_ref() }

    pub fn is_deleted(&self) -> bool { self.metadata.deleted_at.is_some() }

    pub fn is_active(&self) -> bool { self.metadata.deleted_at.is_none() }

    pub fn deleted_at(&self) -> Option<&DateTime<Utc>> { self.metadata.deleted_at.as_ref() }

    pub fn created_by(&self) -> Option<&Uuid> { self.metadata.created_by.as_ref() }

    pub fn updated_by(&self) -> Option<&Uuid> { self.metadata.updated_by.as_ref() }

    pub fn deleted_by(&self) -> Option<&Uuid> { self.metadata.deleted_by.as_ref() }

    /// Set the description field (chainable)
    pub fn with_description(mut self, value: String) -> Self {
        self.description = Some(value);
        self
    }

    /// Apply partial updates from a map of field name to JSON value
    pub fn apply_patch(&mut self, fields: std::collections::HashMap<String, serde_json::Value>) {
        for (key, value) in fields {
            match key.as_str() {
                "name" => {
                    if let Ok(v) = serde_json::from_value(value) { self.name = v; }
                }
                "description" => {
                    if let Ok(v) = serde_json::from_value(value) { self.description = v; }
                }
                "status" => {
                    if let Ok(v) = serde_json::from_value(value) { self.status = v; }
                }
                _ => {}
            }
        }
    }

    // <<< CUSTOM METHODS START >>>
    // <<< CUSTOM METHODS END >>>
}

impl super::Entity for Example {
    type Id = Uuid;

    fn entity_id(&self) -> &Self::Id { &self.id }

    fn entity_type() -> &'static str { "Example" }
}

impl backbone_core::PersistentEntity for Example {
    fn entity_id(&self) -> String { self.id.to_string() }
    fn set_entity_id(&mut self, id: String) {
        if let Ok(uuid) = uuid::Uuid::parse_str(&id) {
            self.id = uuid;
        }
    }
    fn created_at(&self) -> Option<chrono::DateTime<chrono::Utc>> { self.metadata.created_at }
    fn set_created_at(&mut self, ts: chrono::DateTime<chrono::Utc>) { self.metadata.created_at = Some(ts); }
    fn updated_at(&self) -> Option<chrono::DateTime<chrono::Utc>> { self.metadata.updated_at }
    fn set_updated_at(&mut self, ts: chrono::DateTime<chrono::Utc>) { self.metadata.updated_at = Some(ts); }
    fn deleted_at(&self) -> Option<chrono::DateTime<chrono::Utc>> { self.metadata.deleted_at }
    fn set_deleted_at(&mut self, ts: Option<chrono::DateTime<chrono::Utc>>) { self.metadata.deleted_at = ts; }
}

impl backbone_orm::EntityRepoMeta for Example {
    fn column_types() -> std::collections::HashMap<String, String> {
        let mut m = std::collections::HashMap::new();
        m.insert("id".to_string(), "uuid".to_string());
        m.insert("status".to_string(), "example_status".to_string());
        m
    }
    fn search_fields() -> &'static [&'static str] {
        &["name", "description"]
    }
}

/// Builder for Example entity
#[derive(Debug, Clone, Default)]
pub struct ExampleBuilder {
    name: Option<String>,
    description: Option<String>,
    status: Option<ExampleStatus>,
}

impl ExampleBuilder {
    pub fn name(mut self, value: String) -> Self {
        self.name = Some(value);
        self
    }

    pub fn description(mut self, value: String) -> Self {
        self.description = Some(value);
        self
    }

    pub fn status(mut self, value: ExampleStatus) -> Self {
        self.status = Some(value);
        self
    }

    pub fn build(self) -> Result<Example, String> {
        let name = self.name.ok_or_else(|| "name is required".to_string())?;

        Ok(Example {
            id: Uuid::new_v4(),
            name,
            description: self.description,
            status: self.status.unwrap_or(ExampleStatus::default()),
            metadata: AuditMetadata::default(),
        })
    }
}
