//! Auth configuration for Call handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Call>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CallService;
use crate::domain::entity::Call;

/// Permission string constants for Call operations.
pub mod permissions {
    pub const LIST:        &str = "call:list";
    pub const READ:        &str = "call:read";
    pub const CREATE:      &str = "call:create";
    pub const UPDATE:      &str = "call:update";
    pub const DELETE:      &str = "call:delete";
    pub const RESTORE:     &str = "call:restore";
    pub const TRASH:       &str = "call:trash";
    pub const EMPTY_TRASH: &str = "call:empty_trash";
    pub const BULK_CREATE: &str = "call:bulk_create";
    pub const UPSERT:      &str = "call:upsert";
}

/// Resource policy for Call — maps CRUD actions to permission strings.
pub struct CallPolicy;

#[async_trait]
impl ResourcePolicy<Call> for CallPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Call,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Call handlers.
///
/// Wraps `CallService` and checks `CallPolicy` before delegating.
pub type CallGuard = PermissionGuard<Call>;

/// Service-integrated permission guard for Call (for use in generated handlers).
pub type CallServiceGuard = ServicePermissionGuard<Call, CallService, CallPolicy>;

// <<< CUSTOM
// END CUSTOM
