//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod call_auth;

pub use call_auth::{CallPolicy, CallGuard, CallServiceGuard};

// <<< CUSTOM
// END CUSTOM
