//! Call API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Call CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CALL TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Call
pub struct CallTestData;

impl TestDataGenerator for CallTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "direction": "inbound",
            "from_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "to_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "party_id": null,
            "agent_id": null,
            "status": "ringing",
            "external_id": null,
            "subject_type": null,
            "subject_id": null,
            "started_at": now,
            "answered_at": now,
            "ended_at": now,
            "duration_seconds": 1,
            "recording_url": null,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "direction": "inbound",
            "from_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "to_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "party_id": null,
            "agent_id": null,
            "status": "ringing",
            "external_id": null,
            "subject_type": null,
            "subject_id": null,
            "started_at": now,
            "answered_at": now,
            "ended_at": now,
            "duration_seconds": 1,
            "recording_url": null,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// CALL API TEST
// ============================================================================

/// Call API test suite
pub struct CallApiTest {
    inner: GenericCrudTest<CallTestData>,
}

impl CallApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/calls", "Call");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CallTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CallApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_call_crud() {
        let mut test = CallApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Call specific tests here
// <<< CUSTOM TESTS END >>>
