//! Telephony Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::CallService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Call service
    pub call_service: Arc<CallService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        call_service: Arc<CallService>
    ) -> Self {
        Self {
            call_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::TelephonyModule) -> Self {
        Self {
            call_service: module.call_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    call_service: Option<Arc<CallService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Call service.
    pub fn with_call_service(mut self, service: Arc<CallService>) -> Self {
        self.call_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            call_service: self.call_service.expect("call_service is required"),
        }
    }
}
