//! Data Transfer Objects
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

pub mod example_dto;

pub use example_dto::{
    CreateExampleDto, UpdateExampleDto, PatchExampleDto,
    ExampleResponseDto, ExampleListResponseDto, ExampleSummaryDto,
};
