//! Public events for Telephony module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// CALL EVENTS
// ============================================================================

/// Event published when a Call is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CallCreatedEvent {
    pub id: CallId,
    pub data: CallDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Call is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CallUpdatedEvent {
    pub id: CallId,
    pub data: CallDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Call is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CallDeletedEvent {
    pub id: CallId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Telephony module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum TelephonyEvent {
    CallCreated(CallCreatedEvent),
    CallUpdated(CallUpdatedEvent),
    CallDeleted(CallDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TelephonyEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for TelephonyEventMetadata {
    fn default() -> Self {
        Self {
            module: "telephony",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
