//! Telephony Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Telephony exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use telephony::exports::{CallDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `CallDto` - Data transfer object for Call
/// - `CallSummary` - Summary view of Call
/// - `CallId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `CallCreatedEvent` - Published when Call is created
/// - `CallUpdatedEvent` - Published when Call is updated
/// - `CallDeletedEvent` - Published when Call is deleted
pub struct ExportSummary;
