//! Public services for Telephony module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Telephony module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait TelephonyQueryService: Send + Sync {
    /// Get Call by ID
    async fn get_call(&self, id: CallId) -> Result<Option<CallDto>>;

    /// Get Call summary by ID
    async fn get_call_summary(&self, id: CallId) -> Result<Option<CallSummary>>;

    /// Check if Call exists
    async fn call_exists(&self, id: CallId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of TelephonyQueryService
pub struct TelephonyQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> TelephonyQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
