//! Use case type aliases for Call aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCallDto, UpdateCallDto};
use crate::application::service::CallService;
use crate::domain::entity::Call;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCallUseCase = CreateUseCase<Call, CreateCallDto, CallService>;
pub type UpdateCallUseCase = UpdateUseCase<Call, UpdateCallDto, CallService>;
pub type GetCallUseCase    = GetUseCase<Call, CallService>;
pub type DeleteCallUseCase = DeleteUseCase<Call, CallService>;
pub type ListCallUseCase   = ListUseCase<Call, CallService>;

// <<< CUSTOM
// END CUSTOM
