//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod call_usecases;

pub use call_usecases::{
    CreateCallUseCase, UpdateCallUseCase, GetCallUseCase,
    DeleteCallUseCase, ListCallUseCase,
};

// <<< CUSTOM
// END CUSTOM
