//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod call_handler;

// <<< CUSTOM
pub mod telephony_write_handler;
// END CUSTOM

// Re-exports
pub use call_handler::{create_call_routes, create_call_read_routes, create_call_write_routes};
// <<< CUSTOM
pub use telephony_write_handler::create_telephony_validated_write_routes;
// END CUSTOM
